// <auto-generated />
using System;
using IBKS.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IBKS.Web.Migrations
{
    [DbContext(typeof(IBKSDbContext))]
    partial class IBKSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IBKS.Web.Models.Light", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("TypeId");

                    b.ToTable("Lights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            Name = "Light 1",
                            RoomId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Name = "Light 2",
                            RoomId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            Name = "Light 3",
                            RoomId = 3,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description 4",
                            Name = "Light 4",
                            RoomId = 4,
                            TypeId = 4
                        });
                });

            modelBuilder.Entity("IBKS.Web.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Room 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Room 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Room 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Room 4"
                        });
                });

            modelBuilder.Entity("IBKS.Web.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Type 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Type 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Type 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Type 4"
                        });
                });

            modelBuilder.Entity("IBKS.Web.Models.Light", b =>
                {
                    b.HasOne("IBKS.Web.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBKS.Web.Models.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
